# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-12 04:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='picture/')),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('location', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pictures.Location')),
                ('tags', models.ManyToManyField(blank=True, to='pictures.tags')),
            ],
        ),
    ]
